# Generated by Django 4.2.6 on 2023-10-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='record_id',
            new_name='vennbase_id',
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(related_name='records', to='records.recordtag'),
        ),
    ]
